name: Lập trình cuộc sống
description: Chỉ là blog của một thằng coder
seo_description: Lập trình cuộc sống, blog  về kỹ thuật, rèn luyện kỹ năng và chia sẻ  kinh nghiệm phát triển bản thân dành cho tất cả lập trình viên
avatar: images/logo.gif
baseurl: 
site_url: "https://nguyentest.github.io/laptrinhcuocsong"
default_post_avatar: images/logo.gif
permalink: /:title.html
version: v1.2.0
markdown: kramdown
syntax_highlighter: rouge
sass:
  style: :compressed
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
defaults:
  values:
    layout: "post"
# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  
# paginate
paginate: 15
